- name: Bootstrap EKS nodes
  hosts: eks_nodes
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
    - name: Add Kubernetes repo
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    - name: Install kubectl
      apt:
        name: kubectl
        state: present
    - name: Join Node to Cluster
      shell: kubeadm join {{ kubeadm_join_cmd }}